# frozen_string_literal: true

require_relative "test_helper"

# Every assertion here compares this gem with what upstream Python actually answered. The
# fixtures are regenerated by tools/make_parity_fixtures.py, so a change on either side surfaces
# as a failure rather than as a quiet divergence.
class LangParityTest < Minitest::Test
  def setup
    @fixture = LayaTest.parity("lang")
  end

  def test_script_detection_matches_upstream
    @fixture["texts"].each do |row|
      assert_equal row["script"], Laya::Lang.detect_script(row["text"]), row["text"].inspect
    end
  end

  def test_script_profile_matches_upstream
    @fixture["texts"].each do |row|
      profile = Laya::Lang.script_profile(row["text"])
      assert_equal row["profile"].keys.sort, profile.keys.sort, row["text"].inspect
      row["profile"].each { |script, share| assert_in_delta share, profile[script], 1e-9 }
    end
  end

  def test_language_guess_matches_upstream
    @fixture["texts"].each do |row|
      assert_value row["guess"], Laya::Lang.guess_latin_language(row["text"]), row["text"].inspect
    end
  end

  def test_is_english_matches_upstream
    @fixture["texts"].each do |row|
      assert_equal row["is_english"], Laya::Lang.english?(row["text"]), row["text"].inspect
      assert_equal row["is_english"], Laya.english?(row["text"])
    end
  end

  def test_analyse_matches_upstream
    @fixture["texts"].each do |row|
      assert_payload row["analyse"], Laya::Lang.analyse(row["text"]), row["text"].inspect
    end
  end

  def test_state_flattening_matches_upstream
    @fixture["states"].each do |row|
      assert_equal row["text"], Laya::Lang.state_text(row["state"]), row["state"].inspect
      assert_payload row["analyse"], Laya::Lang.analyse(row["state"]), row["state"].inspect
    end
  end

  def test_state_text_is_truncated_like_upstream
    assert_equal @fixture["long_state_text_length"], Laya::Lang.state_text("x" * 5000).length
  end

  def test_symbol_keys_and_values_are_read_like_strings
    assert_equal Laya::Lang.analyse({ "body" => "मुझसे दो बार" }), Laya::Lang.analyse({ body: "मुझसे दो बार" })
  end
end

class EmailParityTest < Minitest::Test
  def setup
    @fixture = LayaTest.parity("email")
  end

  def test_cleaning_matches_upstream
    @fixture["bodies"].each do |row|
      assert_equal row["clean"], Laya::Email.clean_email_body(row["body"]), row["body"].inspect[0, 120]
    end
  end

  def test_email_state_matches_upstream
    @fixture["states"].each do |row|
      subject, body, sender = row["args"]
      options = row["kwargs"].transform_keys(&:to_sym)
      state = Laya.email_state(subject, body, sender: sender, **options)
      assert_payload row["state"], state
    end
  end

  def test_max_chars_matches_upstream
    limits = @fixture["max_chars"]
    assert_equal limits["length"], Laya.clean_email_body(limits["body"]).length
    assert_equal limits["custom"], Laya.clean_email_body("x" * 10, max_chars: 5).length
  end
end

class QuestionParityTest < Minitest::Test
  def setup
    @fixture = LayaTest.parity("questions")
  end

  def test_rendered_options_match_upstream
    @fixture["questions"].each do |name, row|
      question = Laya::Question.build(name, row["definition"])
      assert_equal row["internal_type"], question.type, name
      assert_equal row["instructions"], question.instructions, name
      assert_equal row["options"], question.options, name
    end
  end

  def test_symbol_keyed_definitions_render_the_same
    @fixture["questions"].each do |name, row|
      symbolized = row["definition"].transform_keys(&:to_sym)
      assert_equal row["options"], Laya::Question.build(name, symbolized).options, name
    end
  end

  def test_unanswerable_questions_are_rejected_like_upstream
    @fixture["errors"].each do |name, message|
      refute_nil message, "upstream accepted #{name}, so this fixture needs rewriting"
      error = assert_raises(ArgumentError, name) { Laya::Question.build(name, bad_definition(name)) }
      assert_includes error.message, name, "the message must name the question"
    end
  end

  def test_criterion_rendering_matches_upstream
    criteria = @fixture["criteria"]
    assert_equal criteria["str"], Laya::Common.render_criterion("phishing or scam")
    assert_equal criteria["dict"], Laya::Common.render_criterion({ "desc" => "phishing" })
    assert_equal criteria["list"], Laya::Common.render_criterion(%w[a b])
    assert_equal criteria["int"], Laya::Common.render_criterion(3)
    assert_equal criteria["bool"], Laya::Common.render_criterion(false)
    assert_equal criteria["nonascii"], Laya::Common.render_criterion({ "d" => "münchen" })
  end

  def test_state_serialization_matches_upstream
    @fixture["serialize_state"].each do |json, expected|
      assert_equal expected, Laya::Common.serialize_state(JSON.parse(json))
    end
  end

  private

  # The definitions upstream rejected, kept here because JSON cannot carry a non-Hash definition.
  def bad_definition(name)
    {
      "not_a_dict" => "nope",
      "no_type" => { "instructions" => "x" },
      "unknown_type" => { "type" => "essay", "instructions" => "x" },
      "no_instructions" => { "type" => "noul" },
      "choice_no_criteria" => { "type" => "choice", "instructions" => "x" },
      "choice_empty" => { "type" => "choice", "instructions" => "x", "criteria" => {} },
      "score_not_list" => { "type" => "score", "instructions" => "x", "criteria" => { "a" => 1 } },
      "score_empty" => { "type" => "score", "instructions" => "x", "criteria" => [] },
      "noul_bad_criteria" => { "type" => "noul", "instructions" => "x", "criteria" => ["a"] }
    }.fetch(name)
  end
end

class CalibrationParityTest < Minitest::Test
  def setup
    @fixture = LayaTest.parity("calibration")
  end

  def test_confidence_matches_upstream
    @fixture["confidence"].each do |row|
      assert_in_delta row["confidence"], Laya::Common.confidence_from_probs(row["p"], row["k"]), 1e-12,
                      row.inspect
    end
  end

  def test_ece_matches_upstream
    @fixture["ece"].each do |row|
      got = Laya::Common.ece_score(row["conf"], row["correct"], bins: row["bins"])
      if row["ece"].nil?
        assert got.nan?, "expected NaN for #{row.inspect}"
      else
        assert_in_delta row["ece"], got, 1e-12, row.inspect
      end
    end
  end

  def test_temperature_buckets_match_upstream
    @fixture["buckets"].each do |row|
      assert_equal row["bucket"], Laya::Common.temp_bucket(row["qtype"], row["k"]), row.inspect
      assert_equal row["bucket"], Laya::Common.temp_bucket(Laya::QTYPES[row["qtype"]], row["k"])
    end
  end

  def test_temperature_clamping_matches_upstream
    inputs = { "0.1006" => 0.1006, "0.10058280825614929" => 0.10058280825614929,
               "1.7601518630981445" => 1.7601518630981445, "1.0" => 1.0, "9.0" => 9.0, "0.0" => 0.0,
               "-3.0" => -3.0, "None" => nil, "'x'" => "x", "nan" => Float::NAN,
               "inf" => Float::INFINITY, "'1.5'" => "1.5", "True" => true }
    @fixture["clamps"].each do |row|
      next unless inputs.key?(row["input"])

      assert_in_delta row["clamped"], Laya::Common.clamp_temperature(inputs[row["input"]]), 1e-12, row.inspect
    end
  end
end

class RouterParityTest < Minitest::Test
  def setup
    @fixture = LayaTest.parity("router")
    @questions = {
      "generic" => { "dept" => { "type" => "choice", "instructions" => "Which team?",
                                 "criteria" => { "billing" => nil, "tech" => nil } } },
      "td" => %w[action category churn_risk needs_human urgency]
              .to_h { |id| [id, { "type" => "noul", "instructions" => "x" }] }
    }
    @routers = {
      "default" => Laya::Router.new,
      "auto" => Laya::Router.new(auto_task_detection: true),
      "standalone" => Laya::Router.new(standalone_repos: true),
      "local" => Laya::Router.new(models: { "english" => "/tmp/en", "multilingual" => "/tmp/ml" })
    }
  end

  def test_every_routing_decision_matches_upstream
    @fixture["routes"].each do |row|
      options = row["kwargs"].transform_keys(&:to_sym)
      decision = @routers.fetch(row["router"]).route(row["state"], @questions.fetch(row["questions"]), **options)
      assert_payload ruby_quoted(row["decision"]), decision.to_h,
                     "#{row['router']} #{row['state'].inspect[0, 60]} #{row['kwargs'].inspect}"
    end
  end

  # Upstream writes a quoted value into its reason with Python's repr, which single-quotes
  # strings. The wording is pinned; only the quote character is ours.
  def ruby_quoted(decision)
    decision.merge("reason" => decision["reason"].gsub(/'([^']*)'/) { %("#{Regexp.last_match(1)}") })
  end

  def test_defaults_match_upstream
    assert_equal @fixture["defaults"]["max_loaded"], Laya::Router.new.max_loaded
    assert_equal @fixture["defaults"]["default"], Laya::Router.new.default
    assert_payload @fixture["custom_default"],
                   Laya::Router.new(default: "multilingual").route("12345", @questions["generic"]).to_h
  end

  def test_workflow_matching_matches_upstream
    signatures = {
      "agent_trace_observability" => %w[action needs_review outcome risk urgency],
      "customer_service" => %w[action category churn_risk needs_human urgency],
      "invoice_processing" => %w[discrepancy_severity disposition duplicate matches_order urgency],
      "security_incidents" => %w[credential_compromise disposition severity true_positive urgency]
    }
    @fixture["workflows"].each do |name, expected|
      questions = case name
                  when "partial" then { "urgency" => {}, "category" => {} }
                  when "superset" then (signatures["customer_service"] + ["extra"]).to_h { |i| [i, {}] }
                  when "empty" then {}
                  else signatures.fetch(name).to_h { |i| [i, {}] }
                  end
      assert_value expected, Laya.match_typed_decisions_workflow(questions), name
    end
  end

  def test_aliases_and_repo_strings_match_upstream
    @fixture["aliases"].each { |given, expected| assert_equal expected, Laya.normalise_name(given), given }
    repos = @fixture["repo_str"]
    assert_equal repos["root"], Laya.repo_str([Laya::BUNDLE_REPO, nil])
    assert_equal repos["sub"], Laya.repo_str([Laya::BUNDLE_REPO, "multilingual"])
    assert_equal repos["plain"], Laya.repo_str("some/repo")
  end
end

class PresetsParityTest < Minitest::Test
  def test_presets_match_upstream
    fixture = LayaTest.parity("presets")
    %w[triage_questions email_questions guard_questions moderation_questions router_questions].each do |name|
      assert_payload fixture[name], Laya.public_send(name), name
    end
    assert_payload fixture["email_questions_custom"],
                   Laya.email_questions({ "vip" => "important", "rest" => "everyone else" })
  end

  def test_every_preset_question_renders
    %w[triage_questions email_questions guard_questions moderation_questions router_questions].each do |name|
      Laya.public_send(name).each do |id, definition|
        options = Laya::Question.build(id, definition).options
        refute_empty options, "#{name}/#{id}"
        assert options.all?(String), "#{name}/#{id}"
      end
    end
  end
end

class ShortlistParityTest < Minitest::Test
  # The vectors upstream's fixture was recorded with.
  VECTORS = { "pay me" => [1.0, 0.0], "alpha" => [1.0, 0.0], "beta" => [0.0, 1.0],
              "gamma: mid" => [0.6, 0.8], "delta: same" => [1.0, 0.0] }.freeze
  CRITERIA = { "alpha" => nil, "beta" => "", "gamma" => "mid", "delta" => "same" }.freeze

  def table(vectors)
    calls = []
    embed = lambda do |texts|
      calls << texts.dup
      texts.map { |text| vectors.fetch(text) }
    end
    [embed, calls]
  end

  def test_ranking_matches_upstream
    LayaTest.parity("shortlist")["cases"].each do |row|
      vectors = case row["note"]
                when "zero query" then VECTORS.merge("pay me" => [0.0, 0.0], "delta: same" => [3.0, 4.0])
                when "nan vector" then { "pay me" => [1.0, 0.0], "alpha" => [Float::NAN, Float::NAN],
                                         "beta" => [1.0, 0.0] }
                else VECTORS
                end
      criteria = row["note"] == "nan vector" ? { "alpha" => nil, "beta" => nil } : CRITERIA
      embed, calls = table(vectors)
      assert_equal row["labels"], Laya.shortlist_choice("pay me", criteria, embed, k: row["k"]), row.inspect
      assert_equal row["calls"], calls, "embed_fn call log for #{row.inspect}"
    end
  end

  def test_predict_shortlist_matches_upstream
    fixture = LayaTest.parity("shortlist")["predict"]
    full = { "billing" => { "desc" => "payments" }, "tech" => "bugs", "sales" => nil, "other" => "misc" }
    vectors = { "Which desk?\nI was charged twice" => [1.0, 0.0],
                'billing: {"desc": "payments"}' => [0.0, 1.0], "tech: bugs" => [1.0, 0.0],
                "sales" => [0.2, 0.2], "other: misc" => [0.0, 1.0] }
    seen = nil
    agent = Object.new
    agent.define_singleton_method(:predict) do |_state, questions, **_options|
      seen = questions
      { "model" => "fake", "answers" => {}, "usage" => { "input_tokens" => 1, "output_tokens" => 0 } }
    end
    embed, = table(vectors)
    result = Laya.predict_shortlist(agent, "I was charged twice",
                                    { "intent" => { "type" => "choice", "instructions" => "Which desk?",
                                                    "criteria" => full } }, embed, k: 2)
    assert_payload fixture["shortlist"], result["shortlist"]
    assert_payload fixture["questions_seen"], seen
  end
end
